//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nop.Plugin.Payments.ZonaVirtual.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.zonapagos.com/ws_verificar_pagos/Service.asmx")]
        public string Nop_Plugin_Payments_ZonaVirtual_ZPagosVerificar_Service {
            get {
                return ((string)(this["Nop_Plugin_Payments_ZonaVirtual_ZPagosVerificar_Service"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.zonapagos.com/ws_inicio_pagov2/Zpagos.asmx")]
        public string Nop_Plugin_Payments_ZonaVirtual_ZPagos_ZPagos {
            get {
                return ((string)(this["Nop_Plugin_Payments_ZonaVirtual_ZPagos_ZPagos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.zonapagosdemo.com/ws_inicio_pagov2/Zpagos.asmx")]
        public string Nop_Plugin_Payments_ZonaVirtual_ZPagosDemo_ZPagos {
            get {
                return ((string)(this["Nop_Plugin_Payments_ZonaVirtual_ZPagosDemo_ZPagos"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("https://www.zonapagosdemo.com/ws_verificar_pagos/Service.asmx")]
        public string Nop_Plugin_Payments_ZonaVirtual_ZPagosVerificarDemo_Service {
            get {
                return ((string)(this["Nop_Plugin_Payments_ZonaVirtual_ZPagosVerificarDemo_Service"]));
            }
        }
    }
}
